### ISSUE TITLE
Python exit 0 without raising an exception when calling scipy.linalg.svd([[]]) using the netlib variant of libcblas / libblas / liblapack (on macOS)

### ISSUE THREAD

**Issue by ogrisel** [conda-forge/scipy-feedstock#144]
Using the netlib version of scipy **on macOS**:

```
$ conda create -y -n tmp -c conda-forge scipy blas=*=netlib
$ conda activate tmp
$ python -c "from scipy import linalg; print(linalg.svd([[]]))"
 ** On entry to DGESDD parameter number 10 had an illegal value
$ echo $?
0
```

- conda list:

<details>

```
# packages in environment at /Users/ogrisel/miniconda3/envs/tmp:
#
# Name                    Version                   Build  Channel
blas                      2.0                      netlib    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py39h2c36a5b_2    conda-forge
libblas                   3.9.0           0_h508aa58_netlib    conda-forge
libcblas                  3.9.0           0_h508aa58_netlib    conda-forge
libcxx                    11.0.0               h439d374_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               5.0.0               h7cc5361_13    conda-forge
libgfortran5              9.3.0               h7cc5361_13    conda-forge
liblapack                 3.9.0           0_h508aa58_netlib    conda-forge
liblapacke                3.9.0           0_h508aa58_netlib    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
ncurses                   6.2                  hb1e8313_2    conda-forge
numpy                     1.19.2           py39h948a3a5_1    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
python                    3.9.0           ha017127_4_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
scipy                     1.5.2            py39hea380fd_2    conda-forge
setuptools                49.6.0           py39h2c36a5b_2    conda-forge
sqlite                    3.33.0               h960bd1c_1    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
tzdata                    2020c                h516909a_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```

</details>

while if you install in two steps to get the openblas variants of libblas / libcplas / liblapack (see #143), then I get the exception as expected:

```
$ conda create -y -n tmp -c conda-forge python scipy blas=*=openblas
$ python -c "from scipy import linalg; print(linalg.svd([[]]))"
 ** On entry to DGESDDM parameter number 10 had an illegal value
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ogrisel/miniconda3/envs/tmp/lib/python3.8/site-packages/scipy/linalg/decomp_svd.py", line 121, in svd
    lwork = _compute_lwork(gesXd_lwork, a1.shape[0], a1.shape[1],
  File "/Users/ogrisel/miniconda3/envs/tmp/lib/python3.8/site-packages/scipy/linalg/lapack.py", line 952, in _compute_lwork
    raise ValueError("Internal work array size computation failed: "
ValueError: Internal work array size computation failed: -10
$ echo $?
1
```

- conda list:

<details>

```
# packages in environment at /Users/ogrisel/miniconda3/envs/tmp:
#
# Name                    Version                   Build  Channel
blas                      2.17                   openblas    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py39h2c36a5b_2    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcxx                    11.0.0               h439d374_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               4.0.0               h50e675f_13    conda-forge
libgfortran4              7.5.0               h50e675f_13    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
liblapacke                3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          openmp_h63d9170_5    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
ncurses                   6.2                  hb1e8313_2    conda-forge
numpy                     1.19.2           py39h948a3a5_1    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
python                    3.9.0           ha017127_4_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
scipy                     1.5.2            py39h27fd13a_2    conda-forge
setuptools                49.6.0           py39h2c36a5b_2    conda-forge
sqlite                    3.33.0               h960bd1c_1    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
tzdata                    2020c                h516909a_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```

</details>

So it seems that the netlib lapack python wrapper is broken.

**EDIT**: updated reproducer install commands and conda list output now that #143 has been fixed.

**Comment by ogrisel** [comment]
I also tried to install `conda create -y -n tmp python=3.8 scipy blas=*=netlib` on Linux and I cannot reproduce the problem there (I get the exception as expected). So it seems to be a macOS specific problem.

**Comment by isuruf** [comment]
Can you post `conda list` on both?

**Comment by ogrisel** [comment]
@isuruf I updated the description. It's weird, it's using scipy from the default channel despite the `-c conda-forge` flag...

**Comment by ogrisel** [comment]
@isuruf I have updated the conda list output with today's repo_metadata.json (now that I could confirm that #143 is fixed).

**Comment by ogrisel** [comment]
Note that now that we get the openblas version by default, it's no longer a problem for the scikit-learn CI nor its users as it's very unlikely that anybody will use the netlib version (instead of openblas or MKL). However a buried Python exit 0 is still a very surprising behavior.

**Comment by h-vetinari** [comment]
@ogrisel 
Is this still an issue? I've been testing the scipy test suite against all blas variants (#172, #153 & #130), and there are currently no issues with netlib that I'm aware of. If your case is missing from the upstream test suite, it would be great to get it added there, then it'll automatically show up in the tests I do on the feedstock here. :)

**Comment by h-vetinari** [comment]
Closing as stale
